version: 2.1
jobs:
  build-and-push:
    docker:
      - image: cimg/base:2021.04
        auth:
          username: orca3
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout

      - setup_remote_docker:
          version: 19.03.13
          docker_layer_caching: true

      - run: |
          echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
          ./scripts/build-images-locally.sh
          docker push orca3/services:latest
          docker push orca3/intent-classification-predictor:latest
          docker push orca3/intent-classification:latest
          docker push orca3/intent-classification-torch:latest
          
workflows:
  build:
    jobs:
      - build-and-push:
          context:
            - orca3
