#!/usr/bin/env bash
export MINIO_ROOT_USER=foooo
export MINIO_ROOT_PASSWORD=barbarbar
export MINIO_DM_BUCKET=mini-automl-dm
export MINIO_PORT=9000
export DM_PORT=5000
export PS_PORT=5001
export MS_PORT=5002
export TS_PORT=5003
export REGISTRY_PORT=3000
