# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import data_management_pb2 as data__management__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


class DataManagementServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetDatasetSummary = channel.unary_unary(
                '/data_management.DataManagementService/GetDatasetSummary',
                request_serializer=data__management__pb2.DatasetPointer.SerializeToString,
                response_deserializer=data__management__pb2.DatasetSummary.FromString,
                )
        self.ListDatasets = channel.unary_stream(
                '/data_management.DataManagementService/ListDatasets',
                request_serializer=data__management__pb2.ListQueryOptions.SerializeToString,
                response_deserializer=data__management__pb2.DatasetPointer.FromString,
                )
        self.CreateDataset = channel.unary_unary(
                '/data_management.DataManagementService/CreateDataset',
                request_serializer=data__management__pb2.CreateDatasetRequest.SerializeToString,
                response_deserializer=data__management__pb2.DatasetSummary.FromString,
                )
        self.UpdateDataset = channel.unary_unary(
                '/data_management.DataManagementService/UpdateDataset',
                request_serializer=data__management__pb2.CreateCommitRequest.SerializeToString,
                response_deserializer=data__management__pb2.DatasetSummary.FromString,
                )
        self.PrepareTrainingDataset = channel.unary_unary(
                '/data_management.DataManagementService/PrepareTrainingDataset',
                request_serializer=data__management__pb2.DatasetQuery.SerializeToString,
                response_deserializer=data__management__pb2.SnapshotVersion.FromString,
                )
        self.FetchTrainingDataset = channel.unary_unary(
                '/data_management.DataManagementService/FetchTrainingDataset',
                request_serializer=data__management__pb2.VersionQuery.SerializeToString,
                response_deserializer=data__management__pb2.VersionedSnapshot.FromString,
                )
        self.DeleteDataset = channel.unary_unary(
                '/data_management.DataManagementService/DeleteDataset',
                request_serializer=data__management__pb2.DatasetPointer.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )


class DataManagementServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetDatasetSummary(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListDatasets(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateDataset(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateDataset(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PrepareTrainingDataset(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FetchTrainingDataset(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteDataset(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DataManagementServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetDatasetSummary': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDatasetSummary,
                    request_deserializer=data__management__pb2.DatasetPointer.FromString,
                    response_serializer=data__management__pb2.DatasetSummary.SerializeToString,
            ),
            'ListDatasets': grpc.unary_stream_rpc_method_handler(
                    servicer.ListDatasets,
                    request_deserializer=data__management__pb2.ListQueryOptions.FromString,
                    response_serializer=data__management__pb2.DatasetPointer.SerializeToString,
            ),
            'CreateDataset': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateDataset,
                    request_deserializer=data__management__pb2.CreateDatasetRequest.FromString,
                    response_serializer=data__management__pb2.DatasetSummary.SerializeToString,
            ),
            'UpdateDataset': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateDataset,
                    request_deserializer=data__management__pb2.CreateCommitRequest.FromString,
                    response_serializer=data__management__pb2.DatasetSummary.SerializeToString,
            ),
            'PrepareTrainingDataset': grpc.unary_unary_rpc_method_handler(
                    servicer.PrepareTrainingDataset,
                    request_deserializer=data__management__pb2.DatasetQuery.FromString,
                    response_serializer=data__management__pb2.SnapshotVersion.SerializeToString,
            ),
            'FetchTrainingDataset': grpc.unary_unary_rpc_method_handler(
                    servicer.FetchTrainingDataset,
                    request_deserializer=data__management__pb2.VersionQuery.FromString,
                    response_serializer=data__management__pb2.VersionedSnapshot.SerializeToString,
            ),
            'DeleteDataset': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteDataset,
                    request_deserializer=data__management__pb2.DatasetPointer.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'data_management.DataManagementService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DataManagementService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetDatasetSummary(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/data_management.DataManagementService/GetDatasetSummary',
            data__management__pb2.DatasetPointer.SerializeToString,
            data__management__pb2.DatasetSummary.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListDatasets(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/data_management.DataManagementService/ListDatasets',
            data__management__pb2.ListQueryOptions.SerializeToString,
            data__management__pb2.DatasetPointer.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateDataset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/data_management.DataManagementService/CreateDataset',
            data__management__pb2.CreateDatasetRequest.SerializeToString,
            data__management__pb2.DatasetSummary.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateDataset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/data_management.DataManagementService/UpdateDataset',
            data__management__pb2.CreateCommitRequest.SerializeToString,
            data__management__pb2.DatasetSummary.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def PrepareTrainingDataset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/data_management.DataManagementService/PrepareTrainingDataset',
            data__management__pb2.DatasetQuery.SerializeToString,
            data__management__pb2.SnapshotVersion.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def FetchTrainingDataset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/data_management.DataManagementService/FetchTrainingDataset',
            data__management__pb2.VersionQuery.SerializeToString,
            data__management__pb2.VersionedSnapshot.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteDataset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/data_management.DataManagementService/DeleteDataset',
            data__management__pb2.DatasetPointer.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
